### ISSUE TITLE
Trying to contact owner

### ISSUE THREAD

**Issue by iondodon** [jason-ni/wspty#1]

**Comment by jason-ni** [comment]
What's up buddy?

**Comment by iondodon** [comment]
> What's up buddy?

@jason-ni  I find this small project that you made useful for a project of mine.  It works on linux, but on macos it doesn't work. I made some changes to adjust it for macos... but seems that there are still some problems. Anyway. Would you have some time to help me fix it?

**Comment by jason-ni** [comment]
You can dig into the original [tokio pty implementation](https://github.com/pkgw/stund/blob/master/tokio-pty-process/src/lib.rs#L125). I don't have a Mac dev environment in hand, so I ommited the Mac logic branch.

**Comment by iondodon** [comment]
> You can dig into the original [tokio pty implementation](https://github.com/pkgw/stund/blob/master/tokio-pty-process/src/lib.rs#L125). I don't have a Mac dev environment in hand, so I ommited the Mac logic branch.

Mate you helped me a lot. Thank you! You pointed right into the solution.
